@startuml uml-module-diagram
package "API" {
  class ConverterController
}
package "Main" {}
package "Converter" {
  class Converter
}
package "Parser" {}
package "Validator" {}
package "Domain" {
  interface IUnit
  class UnitFactory
  class UnitRepository
}


ConverterController --> Converter
ConverterController --> UnitRepository
Converter --> IUnit
Converter --> UnitFactory

Main --> IUnit
Main --> Parser
Main --> UnitRepository
Parser --> Validator

@enduml