@startuml

actor User
participant API
participant Converter
participant UnitFactory
participant UnitRepository
database Sqlite

User --> API: Ask to convert 200 m/s (Unit A) to km/h (Unit B)

API --> Converter: Invoke Converter
Converter --> UnitFactory: Request UnitA Object
UnitFactory --> UnitRepository: Request UnitA Entity

UnitRepository --> Sqlite: Database Query
Sqlite --> UnitRepository: Query Result

UnitRepository --> UnitFactory: Return UnitA Entity
UnitFactory --> Converter: UnitA Object


Converter --> UnitFactory: Request UnitB Object
UnitFactory --> UnitRepository: Request UnitB Entity

UnitRepository --> Sqlite: Database Query
Sqlite --> UnitRepository: Query Result

UnitRepository --> UnitFactory: Return UnitB Entity
UnitFactory --> Converter: UnitB Object

Converter --> API: Return Result Object
API --> User: Return Result Object

@enduml